services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
